#include "AlphaBetaAgent.h"

#include "Config.h"
#include "Log.h"
#include "MoveGen.h"
#include "Time.h"
#include "Util.h"

AlphaBetaAgent::AlphaBetaAgent(Board* board, int time) {
  this->board = board;
  this->time = time;
  posCount = moveCount = ttCutoffs = 0;
  Log::debug("Thinking for %d milliseconds", time);
}

Move AlphaBetaAgent::getMove() {
  Move move = iterativeDeepening();
  return move;
}

Move AlphaBetaAgent::iterativeDeepening() {
  short move;
  int score;
  int depth = 0;

  // Randomize the moves at the first level so that the agent picks a random
  // choice from among equals.
  MoveGen moveGen(board, moves[0]);
  moveGen.run();
  if (ALPHA_BETA_RANDOMIZE) {
    moveGen.randomizeMoves();
  }

  // Stop either when the current iteration exceeds the time or when we
  // estimate that the next iteration would be too slow.
  do {
    prevMillis = millis;
    Time::startClock();
    bool inTime = alphaBetaWrapper(++depth, moveGen.numMoves, move, score);
    millis = Time::checkClock();
    time -= millis;
    if (inTime) {
      std::swap(moves[0][0], moves[0][move]);
      logStats(depth, score, millis);
    }
  } while ((score > -WIN_SCORE) && (score < WIN_SCORE) && haveTime());

  return moves[0][0];
}

bool AlphaBetaAgent::haveTime() {
  if (!prevMillis || !millis) {
    return true;
  }

  if (time <= 0) {
    return false;
  }

  // Extrapolate the duration of the next iteration. Be conservative as it may
  // exceed our expectations.
  u64 nextMillis = (u64)millis * millis / prevMillis;
  Log::debug("%d millis remaining; previous 2 iterations took %d and %d millis",
             time, prevMillis, millis);
  Log::debug("Estimated that the next iteration would take %llu millis.",
             nextMillis);
  return (int)nextMillis <= time * 9 / 10;
}

bool AlphaBetaAgent::alphaBetaWrapper(int depth, int numMoves, short& move, int& score) {
  score = -INFTY;

  int i = 0;
  while ((i < numMoves) && (Time::checkClock() < (unsigned)time)) {
    Move m = moves[0][i];
    Board new_b = *board;
    new_b.makeMove(m);
    int child = -alphaBeta(new_b, depth - 1, -INFTY, -score);
    Log::debug("Move %s has score %d at depth %d",
               m.toString().c_str(), child, depth - 1);
    if (child > score) {
      score = child;
      move = i;
    }
    i++;
  }

  if (i < numMoves) {
    Log::notice("alpha-beta ran out of time mid-iteration");
    return false;
  } else {
    return true;
  }
}

int AlphaBetaAgent::alphaBeta(Board b, int depth, int alpha, int beta) {
  if (depth <= 0) {
    posCount++;
    return b.eval();
  }

  TranspositionRecord rec = tt.probe(b.hash);
  if ((rec.depth >= depth) &&
      ((rec.type == TT_EXACT) ||
       ((rec.type == TT_LOWER_BOUND) && (rec.score >= beta)) ||
       ((rec.type == TT_UPPER_BOUND) && (rec.score < alpha)))) {
    ttCutoffs++;
    return rec.score;
  }

  MoveGen moveGen(&b, moves[depth]);
  moveGen.run();
  moveCount++;

  if (!moveGen.numMoves) {
    return b.finalEval();
  }

  bool swapped = false;
  // Account for tt collisions, which can give us the transposition record for
  // a different position. We'll get the ordering wrong, but at least we must
  // not crash.
  if (((rec.type == TT_EXACT) || (rec.type == TT_LOWER_BOUND)) &&
      (rec.move < moveGen.numMoves)) {
    std::swap(moves[depth][0], moves[depth][rec.move]);
    swapped = true;
  }

  Board new_b[TT_PREFETCH_MOVES];
  for (int i = 0; i < moveGen.numMoves && i < TT_PREFETCH_MOVES; i++) {
    Move m = moves[depth][i];
    new_b[i] = b;
    new_b[i].makeMove(m);
    tt.prefetch(new_b[i].hash);
  }

  u8 type = TT_UPPER_BOUND;
  short bestMove = 0;
  for (int i = 0; i < moveGen.numMoves; i++) {
    int j = i % TT_PREFETCH_MOVES;
    // The TT needs to store the original index of the move as generated by
    // the move generator, before the (possible) swap above.
    int orig_i = (swapped && ((i == 0) || (i == rec.move)))
      ? (rec.move - i)
      : i;
    int child = -alphaBeta(new_b[j], depth - 1, -beta, -alpha);

    if (child >= beta) {
      tt.add(b.hash, child, orig_i, depth, TT_LOWER_BOUND);
      return beta;
    } else if (child > alpha) {
      type = TT_EXACT;
      bestMove = orig_i;
      alpha = child;
    }

    // Prefetch move i + TT_PREFETCH_MOVES
    if (i + TT_PREFETCH_MOVES < moveGen.numMoves) {
      new_b[j] = b;
      new_b[j].makeMove(moves[depth][i + TT_PREFETCH_MOVES]);
      tt.prefetch(new_b[j].hash);
    }
  }

  tt.add(b.hash, alpha, bestMove, depth, type);
  return alpha;
}

void AlphaBetaAgent::logStats(int depth, int score, int millis) {
  char s[100];

  if (score >= WIN_SCORE) {
    sprintf(s, "win(%d-%d)",
            score - WIN_SCORE,
            BOARD_SIZE * BOARD_SIZE - (score - WIN_SCORE));
  } else if (score <= -WIN_SCORE) {
    sprintf(s, "lose(%d-%d)",
            BOARD_SIZE * BOARD_SIZE + score + WIN_SCORE,
            -score - WIN_SCORE);
  } else {
    sprintf(s, "%d", score);
  }

  Log::info("depth %d:    %d millis    score %s    %llu positions    %llu calls to movegen    %llu tt cutoffs",
            depth, millis, s, posCount, moveCount, ttCutoffs);
  fprintf(stderr, "kibitz [%s] depth %d / score %s / %llu positions / %llu calls to movegen / %llu tt cutoffs / %d tt evictions\n",
          ENGINE_NAME, depth, s, posCount, moveCount, ttCutoffs, tt.evictions);
}
