#include "AlphaBetaAgent.h"

#include "Config.h"
#include "Log.h"
#include "MoveGen.h"
#include "Time.h"
#include "Util.h"

AlphaBetaAgent::AlphaBetaAgent(Board* board, int time) {
  Time::setAlarm(time);
  this->board = board;
  this->startTime = Time::getTimeMillis();
  if (USE_TRANSPOSITION_TABLES && time >= 100) {
    this->tt = new TranspositionTable();
  } else {
    this->tt = NULL;
  }
  posCount = 0;
  Log::info("Thinking for %d milliseconds", time);
}

Move AlphaBetaAgent::getMove() {
  Move move = iterativeDeepening();
  return move;
}

Move AlphaBetaAgent::iterativeDeepening() {
  short move;
  int score;
  int depth = 0;

  // Randomize the moves at the first level so that the agent picks a random
  // choice from among equals.
  MoveGen moveGen(board, moves[0]);
  moveGen.run();
  if (ALPHA_BETA_RANDOMIZE) {
    moveGen.randomizeMoves();
  }

  // Stop either when the current iteration exceeds the time or when we
  // estimate that the next iteration would be too slow.
  do {
    alphaBetaWrapper(++depth, moveGen.numMoves, move, score);
    if (!Time::checkAlarm()) {
      std::swap(moves[0][0], moves[0][move]);
      logStats(depth, score);
    }
  } while ((score > -WIN_SCORE) && (score < WIN_SCORE) && !Time::checkAlarm());

  return moves[0][0];
}

void AlphaBetaAgent::alphaBetaWrapper(int depth, int numMoves, short& move, int& score) {
  score = -INFTY;

  int i = 0;
  while ((i < numMoves) && !Time::checkAlarm()) {
    Move m = moves[0][i];
    Board new_b = *board;
    new_b.makeMove(m);
    int child = -alphaBeta(new_b, depth - 1, -INFTY, -score);
    Log::debug("Move %s has score %d at depth %d",
               m.toString().c_str(), child, depth - 1);
    if (child > score) {
      score = child;
      move = i;
    }
    i++;
  }
}

int AlphaBetaAgent::alphaBeta(Board b, int depth, int alpha, int beta) {
  if (Time::checkAlarm()) {
    return 0;
  }

  if (depth <= 0) {
    posCount++;
    return b.eval();
  }

  TranspositionRecord rec = ttProbe(b.hash);
  if (rec.isCutoff(depth, alpha, beta)) {
    return rec.score;
  }

  MoveGen moveGen(&b, moves[depth]);
  moveGen.run();

  if (!moveGen.numMoves) {
    return b.finalEval();
  }

  bool swapped = bringBestMoveFirst(rec, depth, moveGen.numMoves);

  Board new_b[TT_PREFETCH_MOVES];
  for (int i = 0; i < moveGen.numMoves && i < TT_PREFETCH_MOVES; i++) {
    prefetchChild(b, moves[depth][i], new_b[i]);
  }

  u8 type = TT_UPPER_BOUND;
  short bestMove = 0;
  for (int i = 0; i < moveGen.numMoves; i++) {
    // The TT needs to store the original index of the move as generated by
    // the move generator, before the (possible) swap above.
    int orig_i = swapped ? twiddle(i, rec.move) : i;
    int j = i % TT_PREFETCH_MOVES;
    int child = -alphaBeta(new_b[j], depth - 1, -beta, -alpha);

    if (child >= beta) {
      ttAdd(b.hash, child, orig_i, depth, TT_LOWER_BOUND);
      return beta;
    } else if (child > alpha) {
      type = TT_EXACT;
      bestMove = orig_i;
      alpha = child;
    }

    // Prefetch move i + TT_PREFETCH_MOVES
    if (i + TT_PREFETCH_MOVES < moveGen.numMoves) {
      prefetchChild(b, moves[depth][i + TT_PREFETCH_MOVES], new_b[j]);
    }
  }

  ttAdd(b.hash, alpha, bestMove, depth, type);
  return alpha;
}

bool AlphaBetaAgent::bringBestMoveFirst(TranspositionRecord rec, int depth,
                                        int numMoves) {
  // Account for tt collisions, which can give us the transposition record for
  // a different position. We'll get the move ordering wrong, but at least we
  // must not crash.
  if (((rec.type == TT_EXACT) || (rec.type == TT_LOWER_BOUND)) &&
      (rec.move < numMoves)) {
    std::swap(moves[depth][0], moves[depth][rec.move]);
    return true;
  } else {
    return false;
  }
}

void AlphaBetaAgent::prefetchChild(Board& src, Move move, Board& dest) {
  dest = src;
  dest.makeMove(move);
  ttPrefetch(dest.hash);
}

int AlphaBetaAgent::twiddle(int a, int x) {
  return ((a == x) || (a == 0)) ? (x - a) : a;
}

TranspositionRecord AlphaBetaAgent::ttProbe(u64 hash) {
  if (tt) {
    return tt->probe(hash);
  } else {
    return { .type = TT_UNKNOWN };
  }
}

void AlphaBetaAgent::ttPrefetch(u64 hash) {
  if (tt) {
    tt->prefetch(hash);
  }
}

void AlphaBetaAgent::ttAdd(u64 key, short score, short move, u8 depth, u8 type) {
  if (tt) {
    tt->add(key, score, move, depth, type);
  }
}

int AlphaBetaAgent::ttEvictions() {
  return tt ? tt->evictions : 0;
}

void AlphaBetaAgent::logStats(int depth, int score) {
  char s[100];

  if (score >= WIN_SCORE) {
    sprintf(s, "win(%d-%d)",
            score - WIN_SCORE,
            BOARD_SIZE * BOARD_SIZE - (score - WIN_SCORE));
  } else if (score <= -WIN_SCORE) {
    sprintf(s, "lose(%d-%d)",
            BOARD_SIZE * BOARD_SIZE + score + WIN_SCORE,
            -score - WIN_SCORE);
  } else {
    sprintf(s, "%d", score);
  }

  int millis = Time::getTimeMillis() - startTime;
  int posPerSec = millis ? (posCount / millis / 1000) : 1;

  fprintf(stderr, "kibitz [%s] depth %d / score %s / %d millis / %llu positions (%d M / sec) / %d tt evictions\n",
          ENGINE_NAME, depth, s, millis, posCount, posPerSec, ttEvictions());
}
